#include "foo.h"
#include "kernels.h"  /* generated by ISPC at configure/build time */
#include <stdio.h>

int main(void) {
    printf("TBMP server sample executable\n");
    foo_print();
    {
        float a[4] = {1.0f, 2.0f, 3.0f, 4.0f};
        float b[4] = {0.5f, 0.5f, 0.5f, 0.5f};
        float out[4] = {0.5f, 0.5f, 0.5f, 0.5f};
        dotProduct(a, b, 4,out);
        printf("After add_f: %f %f %f %f\n", a[0], a[1], a[2], a[3]);
    }
    return 0;
}
