@echo off
REM =============================================================================
REM                             UNITY BUILD SCRIPT 
REM =============================================================================
echo Run Unity Build Script
SETLOCAL ENABLEDELAYEDEXPANSION

rem --- Paths -------------------------------------------------------------------
set "PROJECT_ROOT=%~dp0"
set "BIN_DIR=%PROJECT_ROOT%bin"
set "SRC_DIR=%PROJECT_ROOT%sources"
set "TOOLS_DIR=%PROJECT_ROOT%tools"
set "ISPC=%TOOLS_DIR%\ispc\bin\ispc.exe"

if not exist "%BIN_DIR%" mkdir "%BIN_DIR%"
if not exist "%SRC_DIR%\AutoGenerated" mkdir "%SRC_DIR%\AutoGenerated"

rem --- Parse arguments ---------------------------------------------------------
set "CONFIG=%~1"
set "COMPILER=%~2"
set "USER_CFLAGS=%~3"
set "USER_LDFLAGS=%~4"
set "USER_ISPC_FLAGS=%~5"

echo Config:        %CONFIG%
echo Compiler:      %COMPILER%
echo CFLAGS:        %USER_CFLAGS%
echo LDFLAGS:       %USER_LDFLAGS%
echo ISPC_FLAGS:    %USER_ISPC_FLAGS%

rem --- Defaults ----------------------------------------------------------------
if "%CONFIG%"=="" set "CONFIG=debug"
if /I "%CONFIG%"=="rel" set "CONFIG=release"
if /I "%CONFIG%"=="dbg" set "CONFIG=debug"
if "%COMPILER%"=="" set "COMPILER=clang"

rem Normalize compiler
if /I "%COMPILER%"=="msvc" set "COMPILER=cl"
if /I "%COMPILER%"=="visualc" set "COMPILER=cl"

rem --- Compiler selection -------------------------------------------------------
echo Check compiler tool
if /I "%COMPILER%"=="cl" (
    set "CC=cl"
    set "LINKER=link"
    set "OBJ_EXT=obj"
) else if /I "%COMPILER%"=="gcc" (
    set "CC=gcc"
    set "LINKER=gcc"
    set "OBJ_EXT=o"
) else if /I "%COMPILER%"=="clang" (
    set "CC=clang"
    set "LINKER=clang"
    set "OBJ_EXT=o"
) else (
    echo [ERROR] Unsupported compiler: %COMPILER%
    exit /b 1
)

rem --- Build config -------------------------------------------------------------
echo Set build configuration
if /I "%CONFIG%"=="release" (
    set "TARGET_SUFFIX="
    set "DEFAULT_ISPC_FLAGS=-O2"
) else (
    set "TARGET_SUFFIX=_debug"
    set "DEFAULT_ISPC_FLAGS=-O0 -g"
)

rem --- Compiler-specific defaults ------------------------------------------------
if /I "%COMPILER%"=="cl" (

    if not defined VCINSTALLDIR (
        echo [ERROR] Run inside Visual Studio Developer Command Prompt
        exit /b 1
    )

    if /I "%CONFIG%"=="debug" (
        set "BASE_CFLAGS=/nologo /W3 /Zi /Od /MDd /RTC1 /EHsc /D_DEBUG"
        set "BASE_LDFLAGS=/nologo /DEBUG:FULL /INCREMENTAL:NO"
    ) else (
        set "BASE_CFLAGS=/nologo /W3 /O2 /GL /MD /DNDEBUG"
        set "BASE_LDFLAGS=/nologo /LTCG /OPT:REF /OPT:ICF"
    )

    set "DEFAULT_ISPC_FLAGS=%DEFAULT_ISPC_FLAGS% --arch=x86-64 --target=avx2-i32x8"

) else (

    set "BASE_CFLAGS=-std=c11 -Wall -Wextra"
    if /I "%CONFIG%"=="release" (
        set "BASE_CFLAGS=%BASE_CFLAGS% -O3 -march=native -flto -DNDEBUG"
        set "BASE_LDFLAGS=-flto -s"
    ) else (
        set "BASE_CFLAGS=%BASE_CFLAGS% -O0 -g"
        set "BASE_LDFLAGS=-g"
    )
    set "DEFAULT_ISPC_FLAGS=%DEFAULT_ISPC_FLAGS% --PIC"
)

rem --- Final flags --------------------------------------------------------------
if not "%USER_CFLAGS%."=="."     (set "CFLAGS=%USER_CFLAGS%")         else set "CFLAGS=%BASE_CFLAGS%"
if not "%USER_LDFLAGS%."=="."    (set "LDFLAGS=%USER_LDFLAGS%")      else set "LDFLAGS=%BASE_LDFLAGS%"
if not "%USER_ISPC_FLAGS%."=="." (set "ISPC_FLAGS=%USER_ISPC_FLAGS%") else set "ISPC_FLAGS=%DEFAULT_ISPC_FLAGS%"

set "CFLAGS=%CFLAGS% -I%SRC_DIR%\AutoGenerated"

set "TARGET=%BIN_DIR%\tbmp_server.exe"

echo.
echo =========================================================
echo   Building: %CONFIG% . %COMPILER% . %TARGET%
echo =========================================================
echo.

rem --- Clean -------------------------------------------------------------------
del /Q "%BIN_DIR%\*.*" 2>nul

rem --- ISPC --------------------------------------------------------------------
echo [ISPC] kernels.ispc
"%ISPC%" "%SRC_DIR%\kernels.ispc" -o "%BIN_DIR%\kernels.%OBJ_EXT%" -h "%SRC_DIR%\AutoGenerated\kernels.h" %ISPC_FLAGS% || exit /b 1

rem --- C -----------------------------------------------------------------------
echo [C] Compiling main.c files...
if /I "%COMPILER%"=="cl" (
    cl %CFLAGS% /c "%SRC_DIR%\main.c" /Fd"%BIN_DIR%\vc140.pdb" /Fo"%BIN_DIR%\main.obj" || exit /b 1
) else (
    %CC% %CFLAGS% -c "%SRC_DIR%\main.c" -o "%BIN_DIR%\main.%OBJ_EXT%" || exit /b 1
)

rem --- LINK --------------------------------------------------------------------
echo [LINK] %TARGET%
pushd "%BIN_DIR%"
if /I "%COMPILER%"=="cl" (

    link *.obj %LDFLAGS% /OUT:"%TARGET%" kernel32.lib user32.lib Ws2_32.lib Iphlpapi.lib
) else (
    %LINKER% "%BIN_DIR%\*.%OBJ_EXT%" %LDFLAGS% -lpthread -o "%TARGET%"
)
popd

if %ERRORLEVEL%==0 (
    echo.
    echo ========================================================
    echo   SUCCESS! %TARGET%
    echo ========================================================
) else (
    echo.
    echo XXX BUILD FAILED XXX
    exit /b 1
)

ENDLOCAL
exit /b 0
